### ISSUE TITLE
Make updating easier

### ISSUE THREAD

**Issue by Blaxou** [MisterBianco/BoopSuite#11]
It would be great to just have to do `boop-update` To just update BoopSuite, because the current method is quite long :) (Not that long but no one will ever use it)

**Comment by M1ND-B3ND3R** [comment]
That's a good idea! 
I will begin working on that :) 
Expect that in my next update, thanks for your interest in the project.

**Comment by Sismondi** [comment]
No problem ;)
Very great work !
If I can anything ask me, I would really like to help you (I'm quite good at Python but not as good as you :P)
Otherwise I can help you with other ideas ;D

**Comment by Sismondi** [comment]
Sorry it's my 2nd account ;)

**Comment by M1ND-B3ND3R** [comment]
Okay, was gonna ask XD

**Comment by the-c0d3r** [comment]
Just saw the update code, it's writing a bash script. Since this is a git repository, why not just do a git pull? It would be simpler and cleaner than writing bash script and executing it, no? Cool project btw.
