### ISSUE TITLE
Error in boopsniff.py source

### ISSUE THREAD

**Issue by Mi-Al** [MisterBianco/BoopSuite#15]
Hello! Please, review the strings in **boopsniff.py** file

        if frequency == 2 and channel in xrange(1, 12):
            hop = False;

        elif frequency == "5" and channel in [36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 132, 136, 140, 149, 153, 157, 161, 165]:
            hop = False;

First **(if frequency == 2)** you treat _frequency_ as a number, latter **(frequency == "5")** you treat _frequency_ as a string. So a command like
`sudo boopsniff -i wlan0mon -f 5 -c 100`
will always rise the error:
> [-] Channel Setting incorrect.

**Comment by MisterBianco** [comment]
Awesome thank you, I dont do enough 5ghz testing apparently :) updated and fixed.
