### ISSUE TITLE
killblockingTaks is not defined

### ISSUE THREAD

**Issue by paulv200** [MisterBianco/BoopSuite#20]
Not sure if this an error or if I have not installed it correctly but I get:

killBlockingTasks is not defined NameError global name killBlockingTasks not defined Line 1027 in main

after using:

-S boopsniff -i wlan1mon -k

Paul

**Comment by MisterBianco** [comment]
Thanks for the bug submit, must be something I removed while testing I will have it fixed soon. :)

**Comment by MisterBianco** [comment]
Fixed and pushed!
