### ISSUE TITLE
5Ghz BoopStrike Problem

### ISSUE THREAD

**Issue by c0rndogs** [MisterBianco/BoopSuite#23]
I get the following error when trying to deauth a specific AP (-t) on a specific channel (-c).
```
Traceback (most recent call last):
  File "/usr/local/bin/BoopStrike", line 96, in <module>
    main()
  File "/usr/local/bin/BoopStrike", line 75, in main
    channels = clean_args(args)
  File "/usr/local/bin/BoopStrike", line 49, in clean_args
    channels = [int(x) for x in args['channel'] if int(x) in five_herts]
NameError: global name 'five_herts' is not defined
```

**Comment by MisterBianco** [comment]
OK fixed that and pushed

**Comment by c0rndogs** [comment]
It listens now, but I get this error (assuming when it actually tries to send the deauth):
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/modules/sniffer.py", line 116, in deauther
    send(deauths, inter=float(0.001), count=int(self.mDeauthPackets), verbose=False)
TypeError: int() argument must be a string or a number, not 'NoneType'
```
The command used is:
`BoopStrike -i wlan0 -f 5 -t AA:BB:CC:DD:EE:FF -c 149`
The error flashes and goes away pretty quickly.

**Comment by MisterBianco** [comment]
Thanks a bunch for all the bug reports, I run a very specific set of runs against my network so I don't pick up these cases. I know the solution and will have a fix in about 30 minutes

**Comment by MisterBianco** [comment]
If you want to write errors to a file for me, try running: BoopStrike [args] 2> errorlog.txt

**Comment by MisterBianco** [comment]
OK should be fixed

**Comment by c0rndogs** [comment]
It runs, and it looks like it's trying to deauth, but it's not dropping anything off of the network.  This is basically the same behavior I've gotten with aircrack and wifite when targeting 5Ghz networks as well.  I'm far from pro at this, but I'm not sure the packets are being fully constructed.  I notice in Wireshark that with a valid 2.4Ghz deauth packet, there is a lot of information under the 802.11 radio information section of the header.  While observing deauth packets generated by tools targeting 5Ghz networks, this section is blank.  I'll see if I can brush up on how those exchanges are supposed to work, because I honestly don't know if that's how it's supposed to be or not.

**Comment by MisterBianco** [comment]
Do me a favor and clone my wifijammer-ng repo and see if that deaths the target. It works for me so I am curious

**Comment by c0rndogs** [comment]
Seems like it works, but not consistently.  Can't really put my finger on a pattern.  Might be the hardware I'm testing on.

**Comment by MisterBianco** [comment]
What card are you using?

**Comment by c0rndogs** [comment]
AWUS036ACH.  I think the card works fine, I'm more suspecting my APs.  I have Ubiqiti APs that are broadcasting 3 SSIDs each.  I noticed I get different behavior with the Ubiqiti APs (less reliable) than I do if I just turn the wireless radio on my cable modem on (more reliable) and attack that instead.

**Comment by MisterBianco** [comment]
Hmmm I am not sure, I have some ubiquity routers at work and my tests usually work against them. I will do further testing

**Comment by MisterBianco** [comment]
I am gonna close this issue as resolved let me know if you need it reopened.
